### PR TITLE
repo: Install npm dependencies with the --no-save flag

### PR DESCRIPTION
**Pull request by timmywil**
This fixes https://github.com/jquery/jquery/issues/3947

- Also, I'm not sure `-q` does anything anymore. It's not documented in the [npm install docs](https://docs.npmjs.com/cli/install).

### CODE REVIEW

**Comment by Silic0nS0ldier** [comment]
`-q` sets logging to warnings or greater. Only documented at [their repo](https://github.com/npm/npm/blob/master/doc/misc/npm-config.md) though. Still works as of npm 5.6.0.

**Comment by markelog** [comment]
It is documented, see – https://docs.npmjs.com/misc/config

**Comment by timmywil** [comment]
Maybe our definition of needless differs, but I don't see any needless output. This may differ from older versions because of the new loading animation.

**Comment by markelog** [comment]
That’s a good guess about animation!

I’m fine if you want to land it as is, just wanted to point it out :)

Regards,
Oleg

**Comment by Silic0nS0ldier** [comment]
@markelog Huh. So it is. Was expecting it to be under cli. Thanks for the pointer.

The only thing `-q` seems to suppress under normal use is the `package-lock.json` creation notice, which won't happen anyway due to `--no-save`. It likely also stopped the dependency tree print out in older versions.

Huh. As of v5 of NPM, the [`--save` switch is the default](http://blog.npmjs.org/post/161081169345/v500). Chances are someone updated their version of npm (either directly or via a node update). Another change like this is unlikely to hit again soon (if ever), but it might be worth locking down the npm version if possible.

**Pull request closed without merging**
