### PR TITLE
Replaces 'colors' package with 'chalk'.

### LINKED ISSUE #72: Please use `chalk` instead of `colors.js`
Seems like currently this repo uses the `colors` module to get colors in the terminal. You'd better consider using an alternative, @sindresorhus [chalk](https://github.com/sindresorhus/chalk#why) for example. `colors.js` has many disadvantages (see chalk's readme).

### PR DESCRIPTION
**Pull request by jbnicolai**
Closes #72

### CODE REVIEW

**Comment by jbnicolai** [comment]
Signed the CLA.

**Comment by scottgonzalez** [comment]
Thanks. Can you please update the spacing to match the rest of the code? You can see the full style guide at http://contribute.jquery.org/style-guide/js/.

**Comment by jbnicolai** [comment]
@scottgonzalez I think I've fixed all whitespace and indentation inconsistencies. If there's anything else, let me know.

**Comment by jzaefferer** [comment]
Looks like the author information and the CLA signature don't match: Joshua Appelman != Joshua Boy Nicolai Appelman

We should add jscs to this repository...

**Comment by jzaefferer** [comment]
Diff looks good to me.

**Comment by jbnicolai** [comment]
@jzaefferer ah, made the mistake of signing with my full name. Should be fixed now. 

I'll have a look at adding jscs while I'm at it ;)

**Comment by jbnicolai** [comment]
Seems like the CLA checker still doesn't approve?

**Comment by arthurvr** [comment]
@jbnicolai Your CLA is okay, just checked it. The CLA checker only runs when you push (I think).

**Comment by scottgonzalez** [comment]
Correct. Neither https://github.com/jquery/jquery-license/issues/2 or https://github.com/jquery/jquery-license/issues/6 have been implemented yet.

**Comment by jbnicolai** [comment]
:+1: 

So this can be merged then?

**Comment by jzaefferer** [comment]
Tested locally with `fake-project` and merged.

**Pull request closed without merging**
